# Generated by Django 5.2.5 on 2025-10-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/user_avatars/noavatar.png', upload_to='images/user_avatars'),
        ),
    ]
