/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121490-g7e8ef2ded2-20251024"
#endif /* AVUTIL_FFVERSION_H */
