# Generated by Django 5.2.5 on 2025-08-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.DateField(),
        ),
    ]
