# Generated by Django 5.2.5 on 2025-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0002_alter_track_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default='None', upload_to='images/trackimages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
