# Generated by Django 5.2.5 on 2025-09-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0003_track_image_alter_track_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audiofile',
            field=models.FileField(upload_to='audiofiles'),
        ),
    ]
