# Generated by Django 5.2.5 on 2025-09-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0006_track_liked_by_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='liked_by',
            new_name='like',
        ),
    ]
