# Generated by Django 5.2.5 on 2025-09-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0007_rename_liked_by_track_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='like',
            new_name='liked_by',
        ),
    ]
