# Generated by Django 5.2.5 on 2025-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0008_rename_like_track_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='sections',
            field=models.ManyToManyField(blank=True, to='WaveBox.section'),
        ),
    ]
