# Generated by Django 5.2.5 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0009_section_track_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='WaveBox.track'),
        ),
    ]
