# Generated by Django 5.2.5 on 2025-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0010_section_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='sections',
            field=models.ManyToManyField(blank=True, default=['Popular now'], to='WaveBox.section'),
        ),
    ]
