# Generated by Django 5.2.5 on 2025-10-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Track',
            new_name='track',
        ),
    ]
