# Generated by Django 5.2.5 on 2025-10-18 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0016_remove_track_liked_by_tracklike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='liked_by',
            field=models.ManyToManyField(blank=True, through='WaveBox.TrackLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
