# Generated by Django 5.2.5 on 2025-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0017_track_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklike',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
