# Generated by Django 5.2.5 on 2025-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveBox', '0018_alter_tracklike_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='sclink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
